"""
Canonical Enumerations for Sovereign Trading System

All system state must use these enums. No string literals for state values.
All enums that require JSON serialization inherit from (str, Enum).

This file coordinates with contracts.py and events.py and provides all controlled
categories required by the canonical contracts.
"""

from enum import Enum


class RegimeType(str, Enum):
    """Market regime classification from RegimeDetector."""
    UNKNOWN = "unknown"
    TRENDING_BULL = "trending_bull"
    TRENDING_BEAR = "trending_bear"
    RANGING = "ranging"
    CRISIS = "crisis"


class TruthStatus(str, Enum):
    """Status of TruthFrame reconciliation."""
    RECONCILED = "reconciled"
    DRIFTING = "drifting"
    BROKEN = "broken"


class RiskMode(str, Enum):
    """System-wide risk mode from RiskTruth."""
    NORMAL = "normal"
    SAFE_MODE = "safe_mode"
    HARD_FLAT = "hard_flat"
    REPLAY_ONLY = "replay_only"
    READ_ONLY_DIAGNOSTIC = "read_only_diagnostic"


class OrderSide(str, Enum):
    """Order side. FLAT is not an executable order side."""
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    """Order type."""
    MARKET = "market"
    LIMIT = "limit"
    POST_ONLY = "post_only"


class InternalOrderStatus(str, Enum):
    """
    Normalized internal execution lifecycle state.
    This is the system's authoritative view of order state,
    separate from venue-specific status values.
    """
    CREATED = "created"                 # Intent created, not yet submitted
    SUBMITTED = "submitted"             # Submitted to venue, awaiting ACK
    ACKNOWLEDGED = "acknowledged"       # Venue acknowledged receipt
    OPEN = "open"                       # Working on venue
    PARTIALLY_FILLED = "partially_filled"  # Partially filled, still working
    FILLED = "filled"                   # Fully filled
    CANCELLED = "cancelled"             # Cancelled
    EXPIRED = "expired"                 # Time-to-live expired
    REJECTED = "rejected"               # Venue rejected
    PENDING_CANCEL = "pending_cancel"   # Cancel submitted, awaiting confirmation


class FillStatus(str, Enum):
    """Fill status from reconciliation."""
    PENDING = "pending"                 # Fill received, not yet reconciled
    CONFIRMED = "confirmed"             # Fill confirmed and applied
    RECONCILED = "reconciled"           # Fill reconciled with exchange truth


class CancelStatus(str, Enum):
    """Cancel request status."""
    PENDING = "pending"                 # Cancel submitted
    ACKED = "acked"                     # Cancel acknowledged
    CONFIRMED = "confirmed"             # Cancel confirmed (order no longer working)
    FAILED = "failed"                   # Cancel rejected


class EventType(str, Enum):
    """
    Types of events in the system.
    Stage 0 replay distinguishes raw market data events from derived events.
    """
    # Raw market data events (source: replay files)
    TRADE = "trade"
    QUOTE = "quote"
    ORDER_BOOK_SNAPSHOT = "order_book_snapshot"
    ORDER_BOOK_DELTA = "order_book_delta"
    CLOCK_TICK = "clock_tick"
    
    # Derived events (generated by system)
    FEATURE_VECTOR = "feature_vector"
    STRATEGY_VOTE = "strategy_vote"
    RISK_DECISION = "risk_decision"
    ORDER_INTENT = "order_intent"
    CANCEL_INTENT = "cancel_intent"
    EXECUTION_EVENT = "execution_event"
    FILL_EVENT = "fill_event"
    CANCEL_EVENT = "cancel_event"
    DECISION_RECORD = "decision_record"
    TRUTH_FRAME = "truth_frame"
    DIVERGENCE_EVENT = "divergence_event"
    RECOVERY_CHECKPOINT = "recovery_checkpoint"
    AUDIT_EVENT = "audit_event"         # Audit log entries
    
    # System monitoring events
    HEARTBEAT = "heartbeat"             # System heartbeat monitoring
    
    # Replay control events
    REPLAY_START = "replay_start"       # Marks start of replay session
    REPLAY_END = "replay_end"           # Marks end of replay session


class DivergenceType(str, Enum):
    """Types of divergence between truths."""
    EXCHANGE_EXECUTION = "exchange_execution"
    EXECUTION_PORTFOLIO = "execution_portfolio"
    PORTFOLIO_STRATEGY = "portfolio_strategy"
    STRATEGY_RISK = "strategy_risk"
    TRUTH_CONSENSUS = "truth_consensus"


class ShadowFrontState(str, Enum):
    """ShadowFront strategy state machine states."""
    IDLE = "idle"
    SILENT_ACCUMULATION = "silent_accumulation"
    ARMED = "armed"
    IGNITION = "ignition"
    ACTIVE = "active"
    COOLDOWN = "cooldown"


class LiquidityVoidState(str, Enum):
    """LiquidityVoid strategy state machine states."""
    INACTIVE = "inactive"
    SCANNING = "scanning"
    DETECTED = "detected"
    ENTERED = "entered"
    CLOSED = "closed"


class AlertSeverity(str, Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


class InvariantViolationSeverity(str, Enum):
    """Severity of invariant violation."""
    INFO = "info"
    WARNING = "warning"
    SAFE_MODE = "safe_mode"
    HARD_FLAT = "hard_flat"


class ReplayMode(str, Enum):
    """
    Replay execution mode.
    Stage 0 only requires REPLAY and VERIFY for validation.
    """
    REPLAY = "replay"                   # Replay recorded session
    VERIFY = "verify"                   # Replay and verify against expected outputs


class SourceType(str, Enum):
    """
    Source format for replay data.
    Stage 0 uses JSONL only.
    """
    JSONL = "jsonl"


# ============================================
# ENUMS REQUIRED BY contracts.py
# ============================================

class DecisionType(str, Enum):
    """DecisionRecord decision types."""
    FEATURE_COMPUTE = "feature_compute"
    STRATEGY_VOTE = "strategy_vote"
    RISK_APPROVAL = "risk_approval"
    ORDER_INTENT = "order_intent"
    CANCEL_INTENT = "cancel_intent"
    RECOVERY_ACTION = "recovery_action"


class ExecutionEventType(str, Enum):
    """ExecutionEvent event types."""
    SUBMIT = "submit"
    ACK = "ack"
    REJECT = "reject"
    CANCEL_REQUEST = "cancel_request"
    CANCEL_ACK = "cancel_ack"
    PARTIAL_FILL = "partial_fill"
    FULL_FILL = "full_fill"


class SignalType(str, Enum):
    """StrategyVote signal types."""
    BUY = "buy"
    SELL = "sell"
    FLAT = "flat"
    NO_ACTION = "no_action"


class StrategyID(str, Enum):
    """Strategy identifiers for StrategyVote.strategy_id field."""
    SHADOW_FRONT = "shadow_front"
    LIQUIDITY_VOID = "liquidity_void"


class CheckpointType(str, Enum):
    """RecoveryCheckpoint checkpoint types."""
    WAL_SYNC = "wal_sync"
    TRUTH_FRAME = "truth_frame"
    SNAPSHOT = "snapshot"


class ResolutionType(str, Enum):
    """DivergenceEvent resolution types."""
    PENDING = "pending"
    RECONCILED = "reconciled"
    HARD_FLAT = "hard_flat"
    MANUAL_INTERVENTION = "manual_intervention"


# ============================================
# EXPORTS
# ============================================

__all__ = [
    # Core enums
    'RegimeType',
    'TruthStatus',
    'RiskMode',
    'OrderSide',
    'OrderType',
    'InternalOrderStatus',
    'FillStatus',
    'CancelStatus',
    'EventType',
    'DivergenceType',
    'ShadowFrontState',
    'LiquidityVoidState',
    'AlertSeverity',
    'InvariantViolationSeverity',
    'ReplayMode',
    'SourceType',
    # Contract enums
    'DecisionType',
    'ExecutionEventType',
    'SignalType',
    'StrategyID',
    'CheckpointType',
    'ResolutionType',
]
