"""
Signals — Market Data and Strategy Signal Contracts

Migrated from the unreachable app/models.py into the governed app/models/
package to resolve the Python package-shadowing issue.

Root cause: when app/models.py and app/models/ (package) coexist in the same
directory, CPython always binds 'app.models' to the package directory.
app/models.py becomes permanently unreachable via any standard import path.
DarkPoolPrint, OptionsFlow, and StrategySignal were defined there and were
therefore inaccessible via:
    from app.models import DarkPoolPrint, OptionsFlow, StrategySignal

This file re-establishes those exports within the governed package.

Pydantic version: v2 native (BaseModel, ConfigDict, Field).
Base class: BaseModel with ConfigDict(extra="forbid").
HardenedBaseModel is not used — its only additions over plain BaseModel are
an inert __slots__ = () declaration (no-op on pydantic v2 BaseModel subclasses)
and ConfigDict arguments reproduced here directly.

Governed corrections applied vs app/models.py source:
  StrategySignal.metadata: Dict[str, Any] = {}
    corrected to: Dict[str, Any] = Field(default_factory=dict)
  Reason: bare mutable default raises PydanticUserError in strict pydantic v2.

Hardening applied (session 2):
  StrategySignal.exchange_ts_ns wall-clock default_factory removed.
  Field is now required. All 8 direct call sites under app/ were audited and
  confirmed to supply exchange_ts_ns explicitly before this default was removed.
  Audit evidence: shadow_front.py (×2), liquidity_void.py (×2),
  gamma_front.py (×2), sector_rotation.py (×2).
  Any future StrategySignal construction that omits exchange_ts_ns will raise
  pydantic ValidationError at runtime — correct and intentional.

Float fields: analytical confidence, price, size, and score values.
No monetary computation occurs in these contracts — Decimal is not required.
"""

from typing import Any, Dict, Optional

import numpy as np
from pydantic import BaseModel, ConfigDict, Field

# Machine epsilon — required by StrategySignal.is_actionable
EPS = np.finfo(float).eps


class DarkPoolPrint(BaseModel):
    """Dark pool trade print with nanosecond timestamp."""

    model_config = ConfigDict(extra="forbid")

    symbol: str
    exchange_ts_ns: int
    price: float
    size: float
    exchange: str
    is_buy: bool
    venue: str = "dark_pool"

    @property
    def exchange_ts_sec(self) -> float:
        return self.exchange_ts_ns / 1_000_000_000.0

    @property
    def dollar_value(self) -> float:
        return self.price * self.size


class OptionsFlow(BaseModel):
    """Unusual options activity with nanosecond timestamp."""

    model_config = ConfigDict(extra="forbid")

    symbol: str
    exchange_ts_ns: int
    option_symbol: str
    side: str = Field(pattern="^(CALL|PUT)$")
    volume: int
    open_interest: int
    premium: float
    strike: float
    expiration: int  # Unix timestamp of expiration
    is_unusual: bool

    @property
    def exchange_ts_sec(self) -> float:
        return self.exchange_ts_ns / 1_000_000_000.0

    @property
    def volume_oi_ratio(self) -> float:
        if self.open_interest == 0:
            return float('inf')
        return self.volume / self.open_interest


class StrategySignal(BaseModel):
    """Signal generated by a strategy."""

    model_config = ConfigDict(extra="forbid")

    strategy: str
    symbol: str
    side: str = Field(pattern="^(buy|sell|hold)$")
    confidence: float = Field(ge=0, le=1)
    quantity: float = Field(ge=0)
    price: Optional[float] = None
    # exchange_ts_ns is required — no default.
    # All governed call sites must supply this field explicitly.
    # Wall-clock default_factory removed after full call-site audit confirmed
    # all 8 direct construction sites pass exchange_ts_ns explicitly.
    exchange_ts_ns: int
    reason: str = ""
    metadata: Dict[str, Any] = Field(default_factory=dict)
    regime: Optional[str] = None

    @property
    def exchange_ts_sec(self) -> float:
        return self.exchange_ts_ns / 1_000_000_000.0

    @property
    def is_actionable(self) -> bool:
        return self.side in ["buy", "sell"] and self.quantity > EPS


__all__ = ["DarkPoolPrint", "OptionsFlow", "StrategySignal"]
